apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: josephbaruch-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: josephbaruch-service
            port:
              number: 7999
